core/urls.py
from django.urls import path, include
# from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'core'

"""
After user is authenticated, these are the urls that will be available.
"""
urlpatterns = [
    ## site front to here. 
    path('contact/', views.contact, name='contact'),

    #profile based urls
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile_list', views.profile_list, name='profile_list'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('update_profile/', views.update_user, name='update_profile'),
    path('remove/', views.remove_account, name='remove'),

    #journal based urls.

    #entry based urls.
    path('entries/<int:pk>/', views.entry_landing, name='entry_landing'),
    path('entries/<int:pk>/update_entry/', views.update_entry, name='update_entry'),
    path('entries/<int:pk>/archive/', views.delete_entry, name='archive_entry'),

    #comment based urls
    path('comments/<int:pk>/edit_comment/', views.edit_comment, name='edit_comment'),
    path('comments/<int:pk>/archive_comment/', views.delete_comment, name='archive_comment'),
    path('comments/<int:pk>/reply/', views.reply_comment, name='reply_comment'),

    path('image_upload/', views.image_upload, name='image_upload'),
    path('journals/<int:pk>/', views.journal_profile, name='journal_profile'), 
    path('journals/<int:pk>/dashboard/', views.journal_dashboard, name='journal_dashboard'),
    path('journals/<int:pk>/update/', views.update_journal, name='update_journal'),
    path('journals/<int:pk>/archive/', views.delete_journal, name='delete_journal'),
    path('journals/<int:pk>/create_entry/', views.create_entry, name='create_entry'), 

    path('images/<int:pk>/archive/<int:ok>', views.delete_image, name='archive_image'),

    path('entries/<int:pk>/like/', views.entry_likes, name='entry_likes'),
    path('entries/<int:pk>/unlike/', views.entry_unlike, name='entry_unlike'),
    path('journals/<int:pk>/like/', views.journal_likes, name='journal_likes'),
    path('journals/<int:pk>/unlike/', views.journal_unlike, name='journal_unlike'),
    path('comments/<int:pk>/like/', views.comment_likes, name='comment_likes'),
    path('comments/<int:pk>/unlike/', views.comment_unlike, name='comment_unlike'),
    path('search/users/', views.searchUsers, name='search_users'),
    path('search/', views.search_page, name='search_page'),
    path('search/user/entries/', views.searchUserEntries, name='search_user_entries'),
    path('search/user/journals/', views.searchUserJournals, name='search_user_journals'),
    path('search/entries/', views.searchAllEntries, name='search_all_entries'),
    path('search/journals/', views.searchAllJournals, name='search_all_journals'),
    path('<int:pk>/search/spotify/', views.search_spotify, name='search_spotify'),
    path('entries/<int:pk>/song/', views.add_song, name='add_song'),
    path('upload/', views.upload, name='upload'),
    path('videos/<int:pk>/archive/<int:ok>/', views.delete_video, name='archive_video'),
    path('songs/<int:pk>/archive/<int:ok>/', views.delete_song, name='archive_song'),
    path('places/<int:pk>/archive/<int:ok>/', views.delete_place, name='archive_place'),
    path('entries/<int:pk>/addVideo/', views.another_video, name='add_video'),
    path('<int:pk>/search/location/', views.location_search, name='search_location'),
    path('entries/<int:pk>/place/', views.add_place, name='add_place'),
    path('profiles/<int:pk>/reports/', views.reports, name='reports'),
    path('profiles/<int:pk>/reports/entries_by_day', views.onThisDayReport, name='day_reports'),
    path('spotify_login', views.spotify_login, name="spotify_login"),
    path('profiles/<int:pk>/reports/playlist', views.spotify_report, name='spotify_report'),
    path('profiles/<int:pk>/reports/playlist/range', views.playlist_date_range, name='spotify_report_range'),
    path('profiles/<int:pk>/reports/range', views.memory_date_range, name='report_range'),
    
    path('callback/', views.spotify_callback, name='spotify_callback'),
    ]

social_limn/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from rest_framework import routers
from core import views
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

# Use automatic URL routing for API
# Include login URLS for browsable API

"""
Django's default login/logout as well as password management urls and views
are included under 'accounts/', as we create templates/react for user changing
password, we'll need to reference the Django docs for those urls and views.

The signup url is set up in the project rather than in core because it is "outside"
of our authenticated app-level urls. This structure worked best for redirecting
between login/logout and signup.
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('limn/', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
import requests
import json
import string
import spotipy
from django.contrib.auth import logout as auth_logout, get_user_model
from django.views.decorators.http import require_http_methods
from spotipy.oauth2 import SpotifyOAuth, SpotifyClientCredentials
from django.shortcuts import render, redirect
from .forms import RegisterUserForm, ContactForm, UpdateProfileForm, UpdateUserForm, ImageForm, JournalForm, UpdateJournalForm, EntryForm, CommentForm, SpotifySearchForm, VideoForm, PlaceForm, LocationForm, ReportsForm, OnThisDayForm,OnThisDayRangeForm
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.conf import settings
from django.utils.safestring import mark_safe
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.db.models import Q
from django.contrib.auth.models import User, auth
from django.http import HttpResponse
from rest_framework import viewsets, permissions, status
from rest_framework.response import Response
from .serializers import *
from .models import Profile, Journal, Entry, Image, Comment, Like, Song, Video, Place
from rest_framework.decorators import api_view, renderer_classes
# from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from cloudinary.forms import cl_init_js_callbacks

## helper functions here.
# spotify auth object creation 
def spotify_auth():
    scope = "user-read-recently-played playlist-modify-public user-top-read user-read-playback-position user-read-playback-state user-modify-playback-state user-read-currently-playing user-read-private playlist-modify-private playlist-read-private"
    auth_manager = spotipy.oauth2.SpotifyOAuth(settings.SPOTIPY_CLIENT_ID, settings.SPOTIPY_CLIENT_SECRET, settings.SPOTIPY_REDIRECT_URI,
                                scope=scope)
    return auth_manager

#easy form 
def easy_form(form, dict=None):
    new_thing=form.save(commit=False)
    for key,value in dict.items():
        setattr(new_thing, key, value)
    
    new_thing.save()
    return new_thing

#filter_function
def filter_function(cls, filter_dict, exclude=None, order_by=None):
    if exclude:

        if order_by:
            return cls.objects.filter(**filter_dict).exclude(**exclude).order_by(order_by)
        
        return cls.objects.filter(**filter_dict).exclude(**exclude)
    
    if order_by:
            return cls.objects.filter(**filter_dict).order_by(order_by)
    
    return cls.objects.filter(**filter_dict)
    
#image gallery
def gallery_json(objects, dict, altDict=None, albums=None, check=None):
    jsons = []
    if objects:
        if albums: 
            for obj in objects:
                json_ready = {}
                if len(jsons)== 0 & check==0:
                    album_def = {}

                    for key,value in altDict.items():
                        if value == "image":
                            album_def=obj.image.url
                        elif key=='src':
                            album_def[key] = obj.source_url
                        else:
                            album_def[key]=value

                    jsons.append(json.dumps(album_def))

                for key,value in dict.items():
                    if value == "image":
                        json_ready[key] = obj.image.url
                    elif key =='src':
                        json_ready[key] = obj.source_url
                    else:
                        json_ready[key]=value
                jsons.append(json.dumps(json_ready))
            
        else:
            for obj in objects:
                json_ready={}
                for key,value in dict.items():
                    if value == "image":
                        json_ready[key] = obj.image.url
                    elif key =='src':
                        json_ready[key] = obj.source_url
                    else:
                        json_ready[key]=value
                        
                jsons.append(json.dumps(json_ready))

    return jsons

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]

# Front end views. 

def home(request):

    return render(request, 'sitefront/index.html')


def signup(request):

    if request.method == "POST":
        form = RegisterUserForm(request.POST)
    
        if form.is_valid():
            form.save()
            return redirect('login')
    
    else:
        form = RegisterUserForm()

    return render(request, 'registration/signup.html', {'form':form})


def contact(request):

    if request.method == 'POST':

        form = ContactForm(request.POST)

        if form.is_valid():

            subject = "Limn Message"
            body = {
                "name": form.cleaned_data['name'],
                "message_subject": form.cleaned_data['subject'],
                "email_address": form.cleaned_data['email_address'],
                'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())

            try: 
                send_mail(subject, message, 'maple.megan333@gmail.com', ['maple.megan333@gmail.com'])
            
            except BadHeaderError:
                return HttpResponse('Invalid header')
            
            return redirect("home")
        
    form = ContactForm()
    return render(request, 'sitefront/contact.html', {'form':form})

# Profile and User landing pages.

@login_required(login_url='login')
def dashboard(request):

    entries = Entry.objects.filter(
        journal__user__profile__followed_by__in=
            [request.user.id]).exclude(is_archived=True).order_by('-created_at')
    
    if request.GET.get("code"):
        auth_manager = spotify_auth()
        code = request.GET.get("code", "")
        token = auth_manager.get_access_token(code=code)

    if request.method == "POST":
        form = JournalForm(request.POST, request.FILES)
        if form.is_valid():
            new_journal = easy_form(form, dict={'user':request.user})
            return redirect("core:dashboard")
        
    form = JournalForm()
    frame_key = settings.IFRAME_KEY
    journals = filter_function(Journal, {'user':request.user}, 
            {'is_archived': True})
    return render(request, 'dashboard.html', 
            {'form':form, 'entries':entries, 'journals':journals, 'frame_key':frame_key})

# Edit user and profile pages.

@login_required(login_url='login')
def update_user(request):

    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='core:dashboard')
    
    else:
        user_form=UpdateUserForm(instance=request.user)
        profile_form=UpdateProfileForm(instance=request.user.profile)

    context = {
        'user_form':user_form, 
        'profile_form':profile_form,
    }
    
    return render(request, 'core/update_profile.html', context)

# Archive account also found on the update_profile page. 
@login_required
def remove_account(request):
    user_pk = request.user.pk
    auth_logout(request)
    User = get_user_model()
    User.objects.filter(pk=user_pk).update(is_active=False)
    return redirect(to='core:dashboard')

# Journal 
@login_required(login_url='login')
def journal_profile(request,pk):
    
    journal = Journal.objects.get(pk=pk)
    
    if request.method=='POST':
        commentForm=CommentForm(request.POST)

        if commentForm.is_valid():
            comment = easy_form(commentForm,{'user':request.user, 'journal':journal,})
            return redirect("core:journal_profile", pk=journal.pk)

    commentForm=CommentForm()
    entries = filter_function(Entry,{'journal':journal},exclude={'is_archived':True},order_by='-created_at')
    likes= filter_function(Like,{'journal':journal},{"like":False})
    comments = filter_function(Comment,{'journal':journal},order_by='-created_at')

    likeCounts = {}
    for comment in comments:
        count = Like.objects.filter(comment=comment).exclude(like = False).count()
        likeCounts[comment.id] = count

    context = {
        'journal': journal, 
        'commentForm':commentForm, 
        'comments':comments, 
        'likes':likes, 
        'likeCounts':likeCounts, 
        'entries': entries,
    }

    return render(request, 'core/journal.html', context)

# Journal landing page.
@login_required(login_url='login')
def journal_dashboard(request,pk):

    journal = Journal.objects.get(pk=pk)
    
    if request.user != journal.user:
        return(redirect("core:journal_profile", pk=journal.pk))

    entries = filter_function(Entry,{'journal':journal},exclude={'is_archived':True},order_by='-created_at')
    likes= filter_function(Like,{'journal':journal},{"like":False})

    cal= []
    for entry in entries:
        cal.append({'id': entry.pk,
        'title': entry.title,
        'start':entry.created_at.strftime('%Y-%m-%d'),
        'url': entry.get_html_url})

    context = {
        'journal': journal, 
        'entries': entries, 
        'likes':likes, 
        'cal':cal,
    }

    return render(request, 'core/journal_dashboard.html', context)


# Entry

# Entry Creation.
@login_required(login_url='login')
def create_entry(request,pk):

    journal= Journal.objects.get(pk=pk)

    if request.method == 'POST':

core/templates/core/edit_comment.html
{% extends 'base.html' %}

{% block content %}
<main>
    <section class="row justify-content-center align-items-center">
        <div class="col"></div>
        <div class="col top_spacer">
            <h1>Edit Comment</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{commentForm.as_p}}
                <button type="submit" value="Submit">Edit Comment</button>
            </form>
        </div>
        <div class="col"></div>
    </section>
</main>

{% endblock %}

core/templates/core/journal.html
{% extends 'base.html' %}

{% block content %}
<main>
    {% if journal.is_archived is True%}
        <h1>This journal is not available</h1>
    {% else %}
    <header>
        {% if journal.cover_img %}
        <div class="row background" style="background-image: url('{{ journal.cover_img.url }}')">
            <div class=" row darkOverlay">
                <div class="col"></div>
                <div class="col">
                    <h1>{{journal.title}}</h1>
                    <p>by <a href="{% url 'core:profile' journal.user.profile.pk %}">{{journal.user.username}}</a></p>
                    <p>{{journal.description}}</p>
                </div>
                <div class="col"></div>
                <div class="row">
                    <div class="col"></div>
                    <div class="col">
                    <p>Likes: {{likes.count}}</p>
                    <div class="d-flex">
                        <form action="{% url 'core:journal_likes' pk=journal.pk %}">
                            {% csrf_token %}
                            <button type="submit">Appreciate</button>
                        </form>
                        <form action="{% url 'core:journal_unlike' pk=journal.pk %}">
                            {% csrf_token %}
                        <button type="submit">Unappreciate</button>
                        </form>
                    </div>
                    </div>
                    <div class="col"></div>
                
                </div>
        </div>
        {%else%}
        <div class="col"></div>
            <div class="col-5">
                <h1>{{journal.title}}</h1>
                <p>by <a href="{% url 'core:profile' journal.user.profile.pk %}">{{journal.user.username}}</a></p>
                <p>{{journal.description}}</p>
            </div>
        <div class="col"></div>
        <div class="row">
            <div class="col"></div>
            <p>Likes: {{likes.count}}</p>
            <div class="d-flex">
                <form action="{% url 'core:journal_likes' pk=journal.pk %}">
                    {% csrf_token %}
                    <button type="submit">Appreciate</button>
                </form>
                <form action="{% url 'core:journal_unlike' pk=journal.pk %}">
                    {% csrf_token %}
                <button type="submit">Unappreciate</button>
                </form>
            </div>
            <div class="col"></div>
        </div>
        </div>
        {%endif%}
   
    </header>

    
    <article class="container">
       <div class="row">
        <div class="text-left mb-3">
            <h3>Memory Feed</h3>
        </div>
        <article>
            {% for entry in entries %}
                <a href="{% url 'core:entry_landing' pk=entry.id %}">
                    <div class="row">
                        <div class="col-3">
                            <img src="{{entry.journal.user.profile.profile_img.url}}" class="img-thumbnail" alt="">
                            <p>{{entry.journal.user.username}}</p>
                            <p>{{entry.created_at}}</p>
                        </div>
                    <div class="col-9">
                        <h4>{{entry.title}}</h4>
                        <p>{{entry.journal.title}}</p>
                        {% if entry.image%}
                            {% for img in entry.image.all %}
                                {% if forloop.counter == 1%}
                                    <img src="{{img.image.url}}" class="img-fluid">
                                {% endif%}
                            {% endfor %}
                        {% elif entry.entry_videos %}
                            {% for video in entry.entry_videos.all %}
                                {% if forloop.counter == 1%}
                                <div class="iframely-embed">
                                    <div class="iframely-responsive">
                                        <a data-iframely-url href="{{video.source_url}}"></a>
                                    </div>
                                </div>
                                {% endif%}
                            {% endfor %}
                        {% endif %}
                        <p>{{ entry.body|truncatewords:30 }}</p>
                    </div>
                    </div>
                </a>
            {% endfor %}
        </article>
    </article>
        
    
    <section class="container">
        <div class="row justify-content-center">
        <div class="col"></div>
        <div class="col justify-content-start">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{commentForm.as_p}}
                    <button type="submit" value="submit">Submit</button>
                </form>
        </div>
        <div class="col">
        </div>
    </div>
    </section>

    <section class="container">
    {% if comments.count > 0 %}
        {% for comment in comments %}
        {% if comment.is_parent %}
        <div class="row commentEnd">

            {% if comment.is_archived is True %}
                <div class="row">  
                    <div class="col"></div>
                        <div class="col">
                        <h6>This comment has been deleted</h6>
                        </div>
                    <div class="col"></div>
                </div>
            {%else%}
                    <div class="col-4">
                        <div class="profile-sm">
                            <a href="{% url 'core:profile' pk=comment.user.profile.pk %}">
                                <img src="{{comment.user.profile_img.url}}">
                            </a>
                        </div>
                        <h6>{{comment.user.username}}</h6>
                        <p>{{ comment.created_at }}</p>
                    </div>
                    <div class="col-8">
                        <h5>Comment:</h5>
                        <p>{{comment.comment}}</p>
                    </div>
                    <div class="row">
                        {% for key, value in likeCounts.items %}
                            {% if key == comment.id %}
                                <p>Likes: {{value}}</p>
                            {% endif %}
                        {% endfor %}
                        <div class="d-flex">
                            <form action="{% url 'core:comment_likes' pk=comment.pk %}">
                                {% csrf_token %}
                                <button type="submit">Appreciate</button>
                            </form>
                            <form action="{% url 'core:comment_unlike' pk=comment.pk %}">
                                {% csrf_token %}
                                <button type="submit">Unappreciate</button>
                            </form>
                            {% if request.user == comment.user %}

                                <form action="{% url 'core:archive_comment' pk=comment.pk %}" method="POST">
                                    {% csrf_token %}
                                    <button name="archive" value="archive">Archive</button>
                                </form>
                                <a href="{% url 'core:edit_comment' pk=comment.pk %}"><button>Edit</button></a>

                    {% endif %}
                        </div>
                    </div>
                    
            {%endif%}
            <div class="row">
                <div class="col"></div>
                <div class="row justify-content-center">
                    <form action="{% url 'core:reply_comment' pk=comment.pk %}" method="POST" enctype="multipart/form-data" >
                        {% csrf_token %}
                        {{commentForm.as_p}}
                        <button type="submit" value="submit">Reply to Comment</button>
                    </form>
                </div>
                <div class="col"></div>
            </div>
            {% for child_comment in comment.children %}
            <div class="row commentEnd">
                {% if child_comment.is_archived is True %}
                    <div class="row">  
                        <div class="col"></div>
                            <div class="col">
                            <h6>This comment has been deleted</h6>
                            </div>
                        <div class="col"></div>
                    </div>
                {%else%}
                    <div class="col-1"></div>
                    <div class="col-3">
                        <div class="profile-sm">
                            <a href="{% url 'core:profile' pk=child_comment.user.profile.pk %}">
                                <img src="{{child_comment.user.profile_img.url}}">
                            </a>
                        </div>
                        <h6>{{child_comment.user.username}}</h6>
                        <p>{{child_comment.created_at }}</p>
                    </div>
                    <div class="col-8">
                        <h5>Comment:</h5>
                        <p>{{child_comment.comment}}</p>
                    </div>
                    <div class="row">
                        <div class="col-1"></div>
                        <div class="col-11">
                        {% for key, value in likeCounts.items %}
                            {% if key == child_comment.id %}
                                <p>Likes: {{value}}</p>
                            {% endif %}
                        {% endfor %}
                        <div class="d-flex">
                            <form action="{% url 'core:comment_likes' pk=child_comment.pk %}">
                                {% csrf_token %}
                                <button type="submit">Appreciate</button>
                            </form>
                            <form action="{% url 'core:comment_unlike' pk=child_comment.pk %}">
                                {% csrf_token %}
                                <button type="submit">Unappreciate</button>
                            </form>
                            {% if request.user == comment.user %}

                                <form action="{% url 'core:archive_comment' pk=child_comment.pk %}" method="POST">
                                    {% csrf_token %}
                                    <button name="archive" value="archive">Archive</button>
                                </form>
                                <a href="{% url 'core:edit_comment' pk=child_comment.pk %}"><button>Edit</button></a>

                            {% endif %}
                        </div>
                        </div>
                    </div>
                {%endif%}
                </div>
            </div>
        </div>
    </div>  

        {% endfor %}
        {% endif %}
        {% endfor %}
        
    {% endif %}
    <!--<div id="embed-iframe"></div>-->
</section>
</article>
{% endif %}
</main>

{% endblock %}

core/templates/core/journal_dashboard.html
{% extends 'base.html' %}

{% block content %}
<main>
    {% if journal.is_archived is True %}

        <h1>This journal is no longer available</h1>
    
        {% else %}
        <header class="row">
            {% if journal.cover_img %}
            <div class="row background" style="background-image: url('{{ journal.cover_img.url }}')">
                <div class=" row darkOverlay">
                    <div class="col"></div>
                    <div class="col">
                        <h1>{{journal.title}}</h1>
                        <p>by <a href="{% url 'core:profile' journal.user.profile.pk %}">{{journal.user.username}}</a></p>
                        <p>{{journal.description}}</p>
                    </div>
                    <div class="col"></div>
                    <div class="d-flex justify-content-center">
                            <a href="{% url 'core:update_journal' journal.pk %}">
                                <button>
                                    Edit Journal
                                </button>
                            </a> 
                            <form action="{% url 'core:delete_journal' pk=journal.pk %}" method="POST">
                                {% csrf_token %}
                                <button name="archive" value="archive">Delete Journal</button>
                            </form>
                            <a href="{% url 'core:create_entry' journal.pk %}">
                                <button >
                                    Add Memory
                                </button>
                            </a> 
                    </div>
                </div>
            </div>
            {%else%}
            <div class="col"></div>
                <div class="col-5">
                    <h1>{{journal.title}}</h1>
                    <p>by <a href="{% url 'core:profile' journal.user.profile.pk %}">{{journal.user.username}}</a></p>
                    <p>{{journal.description}}</p>
                </div>
            <div class="col"></div>
            <div class="d-flex justify-content-center">
                
                    <a href="{% url 'core:update_journal' journal.pk %}">
                        <button>
                            Edit Journal
                        </button>
                    </a> 
            
                
                    <form action="{% url 'core:delete_journal' pk=journal.pk %}" method="POST">
                        {% csrf_token %}
                        <button  name="archive" value="archive">Delete Journal</button>
                    </form>
        
                    <a href="{% url 'core:create_entry' journal.pk %}">
                        <button>
                            Add Memory
                        </button>
                    </a> 
            </div>
            {%endif%}

            
        </header>


         
        <article class="container">
        <div class="row">
            <div class="col sticky_top">
                <h5>Memory Log:</h5>
                <div id='calendar'></div>
            </div>
        
        
        <section class="col">
            {% for entry in entries %}
                {% if forloop.first %}
                <div class="row">
                {% endif %}
                {% if entry.image %}
                    {% with entry.image.all|first as image %}
                        <div class="col background" style="background-image: url('{{image.image.url}}');">
                        <div class="row darkOverlay">
                        <div class="col">
                    {% endwith%}
                {%else%}
                    <div class="col-xs-4">
                        <div>
                            <div>
                {%endif%}
                <a href="{% url 'core:entry_landing' pk=entry.pk %}">
                    <h5>{{entry.title}}</h5>
                    </a>
                    <p>{{entry.created_at}}</p> 

                </div></div></div>
            {% if forloop.counter|divisibleby:3 %}
                </div>
                <div class="row">
            {% endif %}
            {% if forloop.last %}
                </div>
            {% endif %}
        {% endfor %}
        
        </div>
        </section>
    </article>
    {% endif %}

</main>
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.4/index.global.min.js'></script>
    <script  type="text/javascript">

    var a = {{cal|safe}};

    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'dayGridMonth', 
        events: a
        });
        calendar.render();
    });

    </script>

{% endblock %}