core/urls.py
from django.urls import path, include
# from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'core'

"""
After user is authenticated, these are the urls that will be available.
"""
urlpatterns = [
    ## site front to here. 
    path('contact/', views.contact, name='contact'),

    #profile based urls
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile_list', views.profile_list, name='profile_list'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('update_profile/', views.update_user, name='update_profile'),
    path('remove/', views.remove_account, name='remove'),

    #journal based urls.

    #entry based urls.
    path('entries/<int:pk>/', views.entry_landing, name='entry_landing'),
    path('entries/<int:pk>/update_entry/', views.update_entry, name='update_entry'),
    path('entries/<int:pk>/archive/', views.delete_entry, name='archive_entry'),

    #comment based urls
    path('comments/<int:pk>/edit_comment/', views.edit_comment, name='edit_comment'),
    path('comments/<int:pk>/archive_comment/', views.delete_comment, name='archive_comment'),
    path('comments/<int:pk>/reply/', views.reply_comment, name='reply_comment'),

    path('image_upload/', views.image_upload, name='image_upload'),
    path('journals/<int:pk>/', views.journal_profile, name='journal_profile'), 
    path('journals/<int:pk>/dashboard/', views.journal_dashboard, name='journal_dashboard'),
    path('journals/<int:pk>/update/', views.update_journal, name='update_journal'),
    path('journals/<int:pk>/archive/', views.delete_journal, name='delete_journal'),
    path('journals/<int:pk>/create_entry/', views.create_entry, name='create_entry'), 

    path('images/<int:pk>/archive/<int:ok>', views.delete_image, name='archive_image'),

    path('entries/<int:pk>/like/', views.entry_likes, name='entry_likes'),
    path('entries/<int:pk>/unlike/', views.entry_unlike, name='entry_unlike'),
    path('journals/<int:pk>/like/', views.journal_likes, name='journal_likes'),
    path('journals/<int:pk>/unlike/', views.journal_unlike, name='journal_unlike'),
    path('comments/<int:pk>/like/', views.comment_likes, name='comment_likes'),
    path('comments/<int:pk>/unlike/', views.comment_unlike, name='comment_unlike'),
    path('search/users/', views.searchUsers, name='search_users'),
    path('search/', views.search_page, name='search_page'),
    path('search/user/entries/', views.searchUserEntries, name='search_user_entries'),
    path('search/user/journals/', views.searchUserJournals, name='search_user_journals'),
    path('search/entries/', views.searchAllEntries, name='search_all_entries'),
    path('search/journals/', views.searchAllJournals, name='search_all_journals'),
    path('<int:pk>/search/spotify/', views.search_spotify, name='search_spotify'),
    path('entries/<int:pk>/song/', views.add_song, name='add_song'),
    path('upload/', views.upload, name='upload'),
    path('videos/<int:pk>/archive/<int:ok>/', views.delete_video, name='archive_video'),
    path('songs/<int:pk>/archive/<int:ok>/', views.delete_song, name='archive_song'),
    path('places/<int:pk>/archive/<int:ok>/', views.delete_place, name='archive_place'),
    path('entries/<int:pk>/addVideo/', views.another_video, name='add_video'),
    path('<int:pk>/search/location/', views.location_search, name='search_location'),
    path('entries/<int:pk>/place/', views.add_place, name='add_place'),
    path('profiles/<int:pk>/reports/', views.reports, name='reports'),
    path('profiles/<int:pk>/reports/entries_by_day', views.onThisDayReport, name='day_reports'),
    path('spotify_login', views.spotify_login, name="spotify_login"),
    path('profiles/<int:pk>/reports/playlist', views.spotify_report, name='spotify_report'),
    path('profiles/<int:pk>/reports/playlist/range', views.playlist_date_range, name='spotify_report_range'),
    path('profiles/<int:pk>/reports/range', views.memory_date_range, name='report_range'),
    
    path('callback/', views.spotify_callback, name='spotify_callback'),
    ]

social_limn/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from rest_framework import routers
from core import views
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

# Use automatic URL routing for API
# Include login URLS for browsable API

"""
Django's default login/logout as well as password management urls and views
are included under 'accounts/', as we create templates/react for user changing
password, we'll need to reference the Django docs for those urls and views.

The signup url is set up in the project rather than in core because it is "outside"
of our authenticated app-level urls. This structure worked best for redirecting
between login/logout and signup.
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('limn/', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
import requests
import json
import string
import spotipy
from django.contrib.auth import logout as auth_logout, get_user_model
from django.views.decorators.http import require_http_methods
from spotipy.oauth2 import SpotifyOAuth, SpotifyClientCredentials
from django.shortcuts import render, redirect
from .forms import RegisterUserForm, ContactForm, UpdateProfileForm, UpdateUserForm, ImageForm, JournalForm, UpdateJournalForm, EntryForm, CommentForm, SpotifySearchForm, VideoForm, PlaceForm, LocationForm, ReportsForm, OnThisDayForm,OnThisDayRangeForm
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.conf import settings
from django.utils.safestring import mark_safe
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.db.models import Q
from django.contrib.auth.models import User, auth
from django.http import HttpResponse
from rest_framework import viewsets, permissions, status
from rest_framework.response import Response
from .serializers import *
from .models import Profile, Journal, Entry, Image, Comment, Like, Song, Video, Place
from rest_framework.decorators import api_view, renderer_classes
# from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from cloudinary.forms import cl_init_js_callbacks

## helper functions here.
# spotify auth object creation 
def spotify_auth():
    scope = "user-read-recently-played playlist-modify-public user-top-read user-read-playback-position user-read-playback-state user-modify-playback-state user-read-currently-playing user-read-private playlist-modify-private playlist-read-private"
    auth_manager = spotipy.oauth2.SpotifyOAuth(settings.SPOTIPY_CLIENT_ID, settings.SPOTIPY_CLIENT_SECRET, settings.SPOTIPY_REDIRECT_URI,
                                scope=scope)
    return auth_manager

#easy form 
def easy_form(form, dict=None):
    new_thing=form.save(commit=False)
    for key,value in dict.items():
        setattr(new_thing, key, value)
    
    new_thing.save()
    return new_thing

#filter_function
def filter_function(cls, filter_dict, exclude=None, order_by=None):
    if exclude:

        if order_by:
            return cls.objects.filter(**filter_dict).exclude(**exclude).order_by(order_by)
        
        return cls.objects.filter(**filter_dict).exclude(**exclude)
    
    if order_by:
            return cls.objects.filter(**filter_dict).order_by(order_by)
    
    return cls.objects.filter(**filter_dict)
    
#image gallery
def gallery_json(objects, dict, altDict=None, albums=None, check=None):
    jsons = []
    if objects:
        if albums: 
            for obj in objects:
                json_ready = {}
                if len(jsons)== 0 & check==0:
                    album_def = {}

                    for key,value in altDict.items():
                        if value == "image":
                            album_def=obj.image.url
                        elif key=='src':
                            album_def[key] = obj.source_url
                        else:
                            album_def[key]=value

                    jsons.append(json.dumps(album_def))

                for key,value in dict.items():
                    if value == "image":
                        json_ready[key] = obj.image.url
                    elif key =='src':
                        json_ready[key] = obj.source_url
                    else:
                        json_ready[key]=value
                jsons.append(json.dumps(json_ready))
            
        else:
            for obj in objects:
                json_ready={}
                for key,value in dict.items():
                    if value == "image":
                        json_ready[key] = obj.image.url
                    elif key =='src':
                        json_ready[key] = obj.source_url
                    else:
                        json_ready[key]=value
                        
                jsons.append(json.dumps(json_ready))

    return jsons

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]

# Front end views. 

def home(request):

    return render(request, 'sitefront/index.html')


def signup(request):

    if request.method == "POST":
        form = RegisterUserForm(request.POST)
    
        if form.is_valid():
            form.save()
            return redirect('login')
    
    else:
        form = RegisterUserForm()

    return render(request, 'registration/signup.html', {'form':form})


def contact(request):

    if request.method == 'POST':

        form = ContactForm(request.POST)

        if form.is_valid():

            subject = "Limn Message"
            body = {
                "name": form.cleaned_data['name'],
                "message_subject": form.cleaned_data['subject'],
                "email_address": form.cleaned_data['email_address'],
                'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())

            try: 
                send_mail(subject, message, 'maple.megan333@gmail.com', ['maple.megan333@gmail.com'])
            
            except BadHeaderError:
                return HttpResponse('Invalid header')
            
            return redirect("home")
        
    form = ContactForm()
    return render(request, 'sitefront/contact.html', {'form':form})

# Profile and User landing pages.

@login_required(login_url='login')
def dashboard(request):

    entries = Entry.objects.filter(
        journal__user__profile__followed_by__in=
            [request.user.id]).exclude(is_archived=True).order_by('-created_at')
    
    if request.GET.get("code"):
        auth_manager = spotify_auth()
        code = request.GET.get("code", "")
        token = auth_manager.get_access_token(code=code)

    if request.method == "POST":
        form = JournalForm(request.POST, request.FILES)
        if form.is_valid():
            new_journal = easy_form(form, dict={'user':request.user})
            return redirect("core:dashboard")
        
    form = JournalForm()
    frame_key = settings.IFRAME_KEY
    journals = filter_function(Journal, {'user':request.user}, 
            {'is_archived': True})
    return render(request, 'dashboard.html', 
            {'form':form, 'entries':entries, 'journals':journals, 'frame_key':frame_key})

# Edit user and profile pages.

@login_required(login_url='login')
def update_user(request):

    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='core:dashboard')
    
    else:
        user_form=UpdateUserForm(instance=request.user)
        profile_form=UpdateProfileForm(instance=request.user.profile)

    context = {
        'user_form':user_form, 
        'profile_form':profile_form,
    }
    
    return render(request, 'core/update_profile.html', context)

# Archive account also found on the update_profile page. 
@login_required
def remove_account(request):
    user_pk = request.user.pk
    auth_logout(request)
    User = get_user_model()
    User.objects.filter(pk=user_pk).update(is_active=False)
    return redirect(to='core:dashboard')

# Journal 
@login_required(login_url='login')
def journal_profile(request,pk):
    
    journal = Journal.objects.get(pk=pk)
    
    if request.method=='POST':
        commentForm=CommentForm(request.POST)

        if commentForm.is_valid():
            comment = easy_form(commentForm,{'user':request.user, 'journal':journal,})
            return redirect("core:journal_profile", pk=journal.pk)

    commentForm=CommentForm()
    entries = filter_function(Entry,{'journal':journal},exclude={'is_archived':True},order_by='-created_at')
    likes= filter_function(Like,{'journal':journal},{"like":False})
    comments = filter_function(Comment,{'journal':journal},order_by='-created_at')

    likeCounts = {}
    for comment in comments:
        count = Like.objects.filter(comment=comment).exclude(like = False).count()
        likeCounts[comment.id] = count

    context = {
        'journal': journal, 
        'commentForm':commentForm, 
        'comments':comments, 
        'likes':likes, 
        'likeCounts':likeCounts, 
        'entries': entries,
    }

    return render(request, 'core/journal.html', context)

# Journal landing page.
@login_required(login_url='login')
def journal_dashboard(request,pk):

    journal = Journal.objects.get(pk=pk)
    
    if request.user != journal.user:
        return(redirect("core:journal_profile", pk=journal.pk))

    entries = filter_function(Entry,{'journal':journal},exclude={'is_archived':True},order_by='-created_at')
    likes= filter_function(Like,{'journal':journal},{"like":False})

    cal= []
    for entry in entries:
        cal.append({'id': entry.pk,
        'title': entry.title,
        'start':entry.created_at.strftime('%Y-%m-%d'),
        'url': entry.get_html_url})

    context = {
        'journal': journal, 
        'entries': entries, 
        'likes':likes, 
        'cal':cal,
    }

    return render(request, 'core/journal_dashboard.html', context)


# Entry

# Entry Creation.
@login_required(login_url='login')
def create_entry(request,pk):

    journal= Journal.objects.get(pk=pk)

    if request.method == 'POST':

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="icon"
      href="https://res.cloudinary.com/limn/image/upload/v1676650217/media/logo/limn-light-favicon.png"
      type="image/png"
    />

    <script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"
    ></script>
    <script src="//cdn.amcharts.com/lib/5/index.js"></script>
    <script src="//cdn.amcharts.com/lib/5/wc.js"></script>
    <script src="//cdn.amcharts.com/lib/5/themes/Animated.js"></script>
    <link
      href="https://cdn.jsdelivr.net/npm/nanogallery2@3/dist/css/nanogallery2.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/nanogallery2@3/dist/jquery.nanogallery2.min.js"
    ></script>
    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Della+Respira&family=Open+Sans:wght@300;400;500&display=swap"
      rel="stylesheet"
    />
    <title>Limn</title>
  </head>
  <body class="bgBackground">
    <div class="darkerOverlay">
      <div id="wrapper">
        {% include 'navbar.html'%} {% block content %} {% endblock %}
      </div>
      {% include 'footer.html' %}
    </div>
    <script src="{% static 'js/index.js' %}"></script>
  </body>
</html>

core/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load widget_tweaks %}

<div class="container">
    {% if user.is_authenticated %}
        <div class="row">
            <!-- <div class="row text-left">
                <h3>Hello, {{ user.username }}!</h3>
                <p>This is your dashboard!</p>
            </div> -->
            <div class="profile-sm user-header">
                <div>
                    <img src="{{ user.profile.profile_img.url }}">
                    {{user.username}}
                </div>
            </div>

            <div class="row">
                <aside class="col-4 text-center profile-col">

                    <div class="mb-3">
                        <!-- <a href="{% url 'core:update_profile' %}"><button >Update Profile</button></a> -->
                        <!-- <a href="{% url 'logout' %}"><button>Logout</button></a> -->
                    </div>
                    <div class="accordion accordion-flush" id="accordion">
                        <div class="accordion-item">
                          <h5 class="accordion-header" id="flush-headingOne">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                                Your Journals
                            </button>
                          </h5>
                          <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body">
                                <div class="d-flex justify-content-center">
                                    <ul>
                                        {% for journal in journals %}
                                            <li>
                                                <a href="{% url 'core:journal_dashboard' pk=journal.pk %}">
                                                    {% if journal.cover_img %}
                                                    <div class="background row" style="background-image: url('{{ journal.cover_img.url }}');">
                                                        <div class="darkOverlay">
                                                            <h6 class="topspace">{{journal.title}}</h6>
                                                            {% if journal.description %}
                                                                <p>{{ journal.description }}</p>
                                                            {% else %}
                                                                <p>No description</p>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                    {% else %}
                                                    <div class="background row" style="background-image: url('https://images.unsplash.com/photo-1528459061998-56fd57ad86e3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=370&q=80');">
                                                        <div class="darkOverlay">
                                                            <h6>{{journal.title}}</h6>
                                                            {% if journal.description %}
                                                                <p>{{ journal.description }}</p>
                                                            {% else %}
                                                                <p>No description</p>
                                                            {% endif %}
                                                        </div>
                                                    </div>

                                                    {% endif %}

                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                          </div>
                        </div>
                        <div class="accordion-item">
                          <h5 class="accordion-header" id="flush-headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                              Create a New Journal
                            </button>
                          </h5>
                          <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body">
                                <div class="row">
                                    <form method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            {{ form.title}}
                                        </div>
                                        <div class="mb-3">
                                            {{ form.location }}
                                        </div>
                                        <div class="mb-3">
                                            {{form.description}}
                                        </div>
                                        <div class="mb-3">
                                            {{form.cover_img}}
                                        </div>
                                        <div class="mb-3">
                                            {{form.default_privacy}}
                                        </div>
                                        <div class="row">
                                            <button type="submit">Submit</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                          </div>
                        </div>
                        
                    </div>
    

                </aside>
                <article class="col memory-feed">

                    <!-- <div class="text-center mb-3 memory-title">
                        <h3>Memory Feed</h3>
                    </div> -->
                    <article>
                        {% for entry in entries %}
                            
                                <div class="row entry-row">
                                    <div class="profile-sm">
                                        <div>
                                            <img src="{{entry.journal.user.profile.profile_img.url}}" class="img-thumbnail" alt="">
                                            {{entry.journal.user.username}}
                                            
                                        </div>
                                            <div>
                                                <p>{{entry.created_at}}</p>
                                            </div>
                                        

                                        
                                    </div>
                                    <a href="{% url 'core:entry_landing' pk=entry.id %}">
                                <div class="row">
                                    {% if entry.image%}
                                        {% for img in entry.image.all %}
                                            {% if forloop.counter == 1%}
                                                <img src="{{img.image.url}}" class="img-fluid">
                                            {% endif%}
                                        {% endfor %}
                                    {% elif entry.entry_videos %}
                                        {% for video in entry.entry_videos.all %}
                                            {% if forloop.counter == 1%}
                                            <div class="iframely-embed">
                                                <div class="iframely-responsive">
                                                    <a data-iframely-url href="{{video.source_url}}"></a>
                                                </div>
                                            </div>
                                            {% endif%}
                                        {% endfor %}
                                    {% endif %}
                                    <h4>{{entry.title}}</h4>
                                    <p>{{entry.journal.title}}</p>
                                    <p>{{ entry.body|truncatewords:30 }}</p>
                                </div>
                            </a>
                                </div>
                            </a>
                        {% endfor %}
                    </article>
                </article>
                    
                
            </div>
        </div>
        <div class="row text-left">
            <div class="col">
    
            </div>
            <div class="col">
            
            </div>
            <div class="col">
                
            </div>
        </div>
    {% else %}
        <div>
            <a href="{% url 'login' %}"><button>Login</button></a>
            <a href="{% url 'signup' %}"><button>Sign Up</button></a>
        </div>
    {% endif %}
</div>

{% endblock %}

<script async src="//cdn.iframe.ly/embed.js?api_key={{frame_key}}"></script>

<script type="text/javascript">
    const url = "https://api.cloudinary.com/v1_1/demo/image/upload";
    const form = document.querySelector("form");

    form.addEventListener("submit", (e) => {
        e.preventDefault();

    const files = document.querySelector("[type=file]").files;
    const formData = new FormData();

    for (let i = 0; i < files.length; i++) {
        let file = files[i];
        formData.append("file", file);
        formData.append("upload_preset", "docs_upload_example_us_preset");

    fetch(url, {
        method: "POST",
        body: formData
    })
    .then((response) => {
        return response.text();
    })
    .then((data) => {
        document.getElementById("data").innerHTML += data;
    });
    }
});
</script>

core/templates/footer.html
<footer class="footer mt-auto py-3">
<div class="container">
    <nav class="navbar navbar-dark">
            
        <a class="nav-link" href="{% url 'home' %}">Home</a>
    
        <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
    
        <a class="nav-link" href="">Kelly Tate</a>
    
        <a class="nav-link" href="">Megan Maple</a>
</nav>
        
</section>

core/templates/navbar.html
{% load static %}
{% block content %}
<nav class="navbar top navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
        <img src="https://res.cloudinary.com/limn/image/upload/v1676733492/media/logo/limn-light-logo-svg.svg" height="80">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        {% if user.is_authenticated %}
            <div class="navbar-nav ms-auto">
                <a class="nav-link active" aria-current="page" href="{% url 'core:dashboard' %}">Dashboard</a>
                <a class="nav-link" href="{% url 'core:profile' pk=request.user.id %}">Profile</a>
                <a class="nav-link" href="{% url 'core:reports' pk=request.user.profile.pk %}">Reports</a>
                <a class="nav-link" href="{% url 'core:search_page' %}">Search</a>
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                
            </div>
        {% else %}
            <div class="navbar-nav ms-auto">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
                <a class="nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
            </div>
        {% endif %}
        </div>
    </div>
</nav>
{% endblock %}